config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # if you want to see the routes & helpers you have drawn out visit http://localhost:3000/rails/info/routes

  # get("/questions", to: "questions#index")
  # get("/questions/new", to: "questions#new", as: :new_question) #adding a `as: :new_question` option to the route will change the helper path name. This is to adhere to rails convention
  # post("/questions", to: "questions#create")

  # # creates a dynamic URL paremter called :id. we can access this dynamic id using params[:id]
  # get("/questions/:id", to: "questions#show", as: :question)
  # delete("/questions/:id", to: "questions#destroy")
  # get("/questions/:id/edit", to: "questions#edit", as: :edit_question)
  # patch("/questions/:id", to: "questions#update")


    # draws routes that look like /api/v1
    namespace :api, defaults: { format: :json } do
      namespace :v1 do
        resources :questions, only: [:index, :show]
  
        resource :session, only: [:create, :destroy]
      end
    end

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  # notice resource here is singular. This is a different method that is like resources.
  # this method is used for a resource which you will only create one of.
  # usually this resource will not need a dynamic id
  # https://api.rubyonrails.org/classes/ActionDispatch/Routing/Mapper/Resources.html#method-i-resource

  # resources :questions #build the CRUD RESTful routes. (all of the above routes for questions)
  # 'resources' method will generate all CRUD routes
  # following RESTful conventions for a resource 
  # It will assume there is a controller named after the
  # first argument, pluralized and PascalCased
  resources :questions do
    resources :likes, shallow: true, only: [:create, :destroy]
    # shallow: true option changes the PATH of the created route
    # Orignal route without shallow: true => /questions/15/likes/20
    # Route with shallow: true => likes/20

    # Routes written inside of a block passed to
    # a resources method will be pre-fixed by 
    # a path corresponding to the passed in symbol. 
    # In this case, all nested routes will be pre-fixed
    # with '/questions/:question_id'
    resources :answers, only: [:create, :destroy]
    # equivalent to: 
    # resources :answers, except: [:show, :index, :new, :edit, :update]
    # question_answers_path(<question-id>)
    # question_answer_url(<question-id>)
    # question_answers_path(@quation)

    get :liked, on: :collection
    # above route creats a path like: GET "/questions/liked" # kind of similar to questions index but only show the questions that the user has liked
  end
  get("/questions/faq", to: "questions#faq")
  # Our application is running on localhost:3000
  # Inside of this is where we define what resources we want available to users
  
  # URL: http://localhost:3000/path
  # HTTP Request are used to interact with our server. They're made up of a HTTP VERB and a PATH
  # VERB     PATH       CONTROLLER    PUBLIC METHOD
  # 👇          👇            👇         👇
  get("/hello_world", to: "welcome#hello_world") # when someone visits GET "/hello_world" they are sent to the welcome controller, hello_world action.

  # GET "/" WelcomeController.root method gets called
  get("/", to: "welcome#root", as: :root)

  # GET "/contact_us"
  get("/contact_us", to: "welcome#contact_us")

  # POST "/process_contact"
  post("/process_contact", to: "welcome#process_contact")
  # delete()
  # patch()
end

app/models/question.rb
class Question < ApplicationRecord
    # This is the Question model. We generated this
    # file with the command:
    # rails g model question title:string body:text
    # This command also generates a migration file in 
    # db/migrate

    # Rails will add att_accessors for all columns
    # of the table (i.e title, body, created_at, updated_at, ...)

    # Adding 'dependent: :destroy' option tells Rails to
    # delete associated records before deleting the record
    # itself. In this case, when a question is deleted,
    # its answers are deleted first to satisfy the foreign 
    # key constraint.
    # You can also use 'dependant: :nullify' which will
    # cause all associated answers to have their question_id
    # column set to NULL before the question is destroyed.

    # if you don't use either depandent options, you can end up
    # with answers in your db referencing question_ids
    # that no longer exist, likely leading to errors. 
    # Always set a dependent option to help maintain
    # referential integrity.
    has_many :taggings, dependent: :destroy 
    has_many :tags, through: :taggings#, source: :tag
    # If the name of the association (i.e. tags) is the same as the
    # source singularized (i.e. tag), then the 'source:' named
    # argument can be omitted

    has_many :likes
    has_many :likers, through: :likes, source: :user
    # has_and_belongs_to_many(
    #     :likes,
    #     class_name: 'User',
    #     join_table: 'likes',
    #     association_foreign_key: 'user_id',
    #     foreign_key: 'question_id'
    # )
    belongs_to :user
    has_many(:answers, dependent: :destroy)
    # has_many(:answers, dependent: :destroy) adds 
    # the following instance methods to the Question model:
    # .answers
    # .answers<<(object, ...)
    # .answers.delete(object, ...)
    # .answers.destroy(object,...)
    # .answers=(object)
    # .answers_singular_ids
    # .answers_singular_ids=(ids)
    # .answers.clear
    # .answers.empty?
    # .answers.size 
    # .answers.find(...)
    # .answers.where(...)
    # .answers.exists?(...)
    # .answers.build(attribute = {}, ...)
    # .answers.create(attributes = {})
    # .answers.create!(attributes = {})
    # .answers.reload

    # V A L I D A T I O N S
    # Create validations by using the 'validates' method
    # Th arguments are (in order):
    # - A column name as a symbol 
    # - Named arguments, corresponding to the validation rules

    # To read more on validations, go to:
    # https://guides.rubyonrails.org/active_record_validations.html

    validates(:title, presence: true, uniqueness: true)
    validates(
        :body,
        presence: { message: "must exist" },
        length: { minimum: 10 }
    )
    validates(
        :view_count,
        numericality: { greater_than_or_equal_to: 0, allow_blank: true }
    )

    # Custom validation
    # The method for custom validations is singular
    # unlike the 'validates' method for regular validations
    validate :no_monkey

    # before_validation is a ifescycle callback
    # method that allows to respond to events during 
    # the life of a model instance (i.e being validated, 
    # being created, being updated etc.)
    # All lifecycle callback methods take a symbol 
    # named after a method and calls that method 
    # at the appropriate time.
    before_validation(:set_default_view_count)

    # For all available methods go to:
    # https://guides.rubyonrails.org/v4.0/active_record_callbacks.html

    # def cool_view_count
    #     view_count 
    # end

    # Create a scope with a class method
    # https://edgeguides.rubyonrails.org/active_record_querying.html#scopes

    # def self.recent
    #     order(created_at: :desc).limit(10)
    # end

    # Scopes are such a commonly used feature, that
    # there's another way to create them quicker. It 
    # takes a name and a lambda as a callback
    scope(:recent, -> { order(created_at: :desc).limit(10)})

    # def self.search(query)
    #     where("title ILIKE ? OR body ILIKE ?", "%#{query}%", "%#{query}%")
    # end

    # Equivalent to:
    scope(:search, -> (query){ where("title ILIKE ? OR body ILIKE ?", "%#{query}%", "%#{query}%") })
 
    def tag_names 
        self.tags.map(&:name).join(", ")
        # The & symbol is used to tell Ruby that the following argument
        # should be treated as a block givent to the method. So the line:
        # self.tags.map(&:name).join(", ")
        # is equivalent to:
        # self.tags.map { |x| x.name }.join(", ")
        # So the above will iterate over the collection self.tags
        # and build an array with the result of the name method 
        # called on every item. (We then join the array into a comma
        # separated string)
    end

    # Appending = at the end of a method name, allows us to implement
    # a 'setter'. A setter is a method that is assignable.
    # Example: 
    # q.tag_names = "stuff, yo"

    # The code in the example above would call the method we wrote 
    # below where the value on the right-hand side of the '=' would 
    # become the argument to the method 

    # This is similar to implementing an 'attr_writer'
    def tag_names=(rhs)
        self.tags = rhs.strip.split(/\s*,\s*/).map do |tag_name| 
            # Finds the first record with the given attributes, or
            # initializes a record (Tag.new) with the attributes
            # if one is not found 
            Tag.find_or_initialize_by(name: tag_name)
            # If a tag with name tag_name is not found,
            # it will call Tag.new(name: tag_name)
        end
    end

    private 
    
    def no_monkey
        # &. is the safe navigation operator. It's used
        # like the . operator to call methods on an object.
        # If the method doesn't exist for the object, 'nil'
        # will be returned instead of getting an error
        if body&.downcase&.include?("monkey")
            # To make a record invalid. You must add a 
            # validation error using the 'errors' 'add' method
            # It's arguments (in order):
            # - A symbol for the invalid column
            # - An error message as a string
            self.errors.add(:body, "Must not have monkeys")
        end
    end

    def set_default_view_count
        self.view_count ||= 10
    end

    def self.all_with_answer_counts
        self
            .left_outer_joins(:answers)
            .select("questions.*", "COUNT(answers.*) AS answers_count")
            .group("questions.id")
            # https://edgeguides.rubyonrails.org/active_record_querying.html#left-outer-joins
    end
    
    
    
    # A C T I V E    R E C O R D 
    # Fetch All Questions
    # questions = Question.all 👈 this will give us back the list of questions as an object
    # the object behaves like an array so you can call methods on it like (.each) and you
    # can also chain it with other methods to do other types of operations and queries

    # Creating a new question
    # To create a new question object in memory do:
    # q = Question.new
    # you can also pass in a hash to the new method as in:
    # q = Question.new({ title: 'To be or not to be', body: 'is that a question?', view_count: 0 })
    # or for short:
    # q = Question.new title: 'To be or not to be }, body: 'is that a question?', view_count: 0 

    # to save the above question into questions table:
    # q.save 👈 this will save that above question into the questions table (persist it)

    # Creating a record right away
    # you can create a record right away in the database using (.create) method as in:
    # Question.create({ title: 'My Question Title', body: 'My question body', view_count: 1 })

    # Fetching Records
    # .first
    # Question.first 👈 fetches the first record ordered by the id in an ascending order
    # The sql equivalent:
    # SELECT "questions".* FROM "questions" ORDER BY "questions"."id" ASC LIMIT 1;

    # .last
    # Question.last 👈 fetches the last record ordered by the id in an ascending order 
    # The sql equivalent:
    # SELECT "questions".* FROM "questions" ORDER BY "qeustions"."id" DESC LIMIT 1;

    # .find
    # Question.find(1) 👈 finding records by their primary key which is likely id

    # .find_by_x 👈 x is the column name
    # Question.find_by_title('My Last Question') 👈 this finds a question with title 
    # exactly "My Last Question"

    # .where
    # Question.where({ title: 'My Last Question', body: 'The body of the question' })

    # WILDCARD SEARCHING 
    # You can perform  wildcard searching with ActiveRecord using LIKE within "where" method
    # Question.where(['title LIKE ?', '%Last%'])
    # if you are using Postgres client, you can use ILIKE for case-insensitive searching:
    # Question.where(['title ILIKE ?', '%Last%'])
    # Note that in above queries we used a syntax that used '?' to insert variable into a SQL query.
    # this is important to avoid SQL injection if the variable component is actually a user input such
    # as search term.

    # .limit
    # Question.limit(10) 👈 this will give us back 10 first questions that are returned from the query

    # .order
    # Question.order(:created_at) 👈 this will order the fetched records by created_at. by default is ASC and 
    # if you want them in descending order do:
    # Question.order(created_at: :DESC)


    # Chaining
    # You can chain the wher, limit, order, offset, and many others to compose
    # more sophisticated queries for example:
    # Question.where(['view_count > ?', 10]).where(['title ILIKE ?', 'a']).order(id: :DESC).limit(10).offset(10)
    # Note: offset will skip first 10 records from the above query
    # SQL equivalent:
    # SELECT "questions".* FROM "questions" WHERE (view_count > 10) AND (title ILIKE 'a') ORDER BY id DESC LIMIT 10 OFFSET 10
    # another example:

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < ApplicationController
    def index
        questions = Question.order(created_at: :desc)
        render json: questions
      end
    
      def show
        # /api/v1/questions/:id
        question = Question.find params[:id]
        render json: question
      end
end

app/controllers/questions_controller.rb
# run `rails g controller questions` to generate a questions controller

class QuestionsController < ApplicationController
  #before_action is a controlle hook provided by rails
  # 1) it accepts a method name
  # 2) options hash
  before_action :authenticate_user!, except: [:index, :show] 
  # will call authenticate_user! before every method except :index and :show
  before_action :authorize!, only: [:edit, :update, :destroy]

  # show all of our questions
  def index
    @questions = Question.all.all_with_answer_counts.order('updated_at DESC')
  end

  def new
    @question = Question.new # we need an instance of our resource to be used with `form_with`
  end

  def create
    # params.require(:question).permit(:title, :body) => tells rails to allow an object on the params that is called question. And on that question object allow the keys :title and :body
    @question = Question.new(params.require(:question).permit(:title, :body, :tag_names))
    @question.user = current_user
    #tell active record to goahead and run the INSERT SQL query against our db. Returns true if it saves, returns false if it doesn't save
    if @question.save
      redirect_to questions_path
    else
      render :new
    end
  end

  def show
    id = params[:id]
    @question = Question.find(id)
    # For the form_with helper 
    @answer = Answer.new 
    # For the list of answer
    @answers = @question.answers.order(created_at: :desc)

    @like = @question.likes.find_by(user: current_user)
  end

  def destroy
    id = params[:id]
    @question = Question.find(id)
    @question.destroy
    redirect_to questions_path
  end

  def edit
    id = params[:id]
    @question = Question.find(id)
  end

  def update
    id = params[:id]
    @question = Question.find(id)
    if @question.update(params.require(:question).permit(:title, :body, :tag_names))
      redirect_to question_path(@question)
    else
      render :edit
    end
  end

  def liked
    # all the questions that this particular logged in user has liked
    @questions = current_user.liked_questions.all_with_answer_counts.order(created_at: :desc)
  end

  private

  def authorize! 
    redirect_to root_path, alert: 'Not Authorized' unless can?(:crud, Question)
  end
end

app/helpers/api/v1/questions_helper.rb
module Api::V1::QuestionsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<% if @question.errors.present? %>
  <p>
    <%= @question.errors.full_messages.join(', ')%>
  </p>
<% end %>

<%# by default rails forms will submit using XHR/AJAX we'll learn this in the future but for now we want to submit using HTML5 forms so we'll have to set the `local` option to true%>
<%# https://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html#method-i-form_with %>
<%= form_with model: @question, local:true do |f| %>
  <div class='form-group'>
    <%= f.label :title %>
    <%= f.text_field(:title, class: 'form-control')%>
  </div>
  <div class='form-group'>
    <%= f.label :body %>
    <%= f.text_area(:body, class: 'form-control', cols: 50, rows: 5)%>
  </div>
  <%# <div class='tag-container'> %>
    <%#= f.collection_check_boxes :tag_ids, Tag.order(name: :asc), :id, :name do |t| %>
      <%# <div class="tag-wrapper"> %>
        <%#= t.check_box %>
        <%#= t.text.humanize %>
      <%# </div> %>
    <%# end %>
  <%# </div> %>

    <%= f.label :tag_names %>
    <%= f.text_field :tag_names %>
  <%= f.submit "Submit", class: 'btn btn-primary' %>
<% end %>

<%# selectize docs:
https://github.com/selectize/selectize.js/blob/master/docs/usage.md
%>

<script>
$(function() {
	$('#question_tag_names').selectize({
    delimeter: ',', 
    persist: false, 
    labelField: 'name',
    valueField: 'name',
    searchField: 'name',
    options: <%= Tag.select(:name).to_json(except: [:id]).html_safe %>,
    // The above line selects only names from Tag table and converts them to a json array of objects
    // without including ids and makes sure its a safe_html string
    // options: [{"name": "firstTag"}, {"name": "secondTag"}, {"name": "thirdTag"}, {"name": "fourthTag"}, {"name": "fifthTag"}]
    create: function(input) {
      return {
        name: input
      }
    }
  });
});
</script>

app/views/questions/_list.html.erb
<ul>
  <% @questions.each do |question| %>
    <%# if you pass a instance to link_to it will create the href='/questions/:id' %>
    <%= link_to question do %>
      <li class='list-group-item'>
        <p><%= question.id %> <%= question.title %></p>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/questions/edit.html.erb
<h1>Edit Question Page</h1>

<%= render 'form' %>

app/views/questions/index.html.erb
<% if @tag.present? %>
  <h2>Showing questions tagged by: <span class="badge badge-pill badge-primary"><%= @tag.name %></span></h2>
<% else %>
<h1>Questions Index Page</h1>
<% end %>
<div class='row'>
  <div class='col-2'>
  </div>

  <div class='col-10'>
    <%= render 'list' %>

    <%# link_to just creates a `a tag` with the correct href. the below is equivalent to the above code %>
    <% if false %>
      <% @questions.each do |question| %>
        <a href="/questions/<%= question.id %>">
          <li class='list-group-item'>
            <p><%= question.id %> <%= question.title%></p>
          </li>
        </a>
      <% end %>
    <% end %>
  </div>
</div>

app/views/questions/liked.html.erb
<h1>Liked Questions page</h1>
<%= render 'list' %>

app/views/questions/new.html.erb
<h1>Question New page</h1>

<%# by default rails forms will submit using XHR/AJAX we'll learn this in the future but for now we want to submit using HTML5 forms so we'll have to set the `local` option to true%>
<%# https://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html#method-i-form_with %>

<%= render 'form' %>

app/views/questions/show.html.erb
<div class='shadow-sm p-3 mb-5 bg-white rounded overflow-wrap'>
  <h1>
    <span class='badge badge-pill badge-info'>
      <%= @question.id %>
    </span>
    <%= @question.title %>
  </h1>
  <p class='shadow-none p-3 mb-5 bg-light rounded'><%= @question.body %></p>
  <p>
  <div class="tags">Tags: <%= @question.tags.map(&:name).join(", ") %></div>
  <%# 
    leEquivant to:
    @question.tags.map { |t| t.name }.join(", ")
   %>
  </p>
  <p class='text-muted'><%= @question.user.first_name %> <%= @question.user.last_name %></p>
  <%# link_to arguments: name, path, options_object %>
  <small>Liked by: <%= @question.likes.count %></small>
  <small>
    <% if @like.present? %>
      <%= link_to(
          "🧡",
          like_path(@like),
          method: :delete
        )
      %>
    <% else %>
      <%= link_to(
          "🤍",
          question_likes_path(@question),
          method: :post
        )
      %>
    <% end %>
  </small>
  <% if can? :crud, @question %>
  <div>
    <%= link_to(
      "Edit",
      edit_question_path(@question),
      class: 'btn btn-info'
    )
    %>
    <%= button_to(
      "Delete",
      question_path(@question),
      method: :delete,
      class: 'btn btn-danger',
      data: { confirm: 'are you sure?' }
    )
    %>
  </div>
  <% end %>
</div>

<%#
  To create a form for a resource (i.e. a model), use the form_with
  helper instead of the form_tag. Its usual arguments are:
  - A named arg. model which is assigned an instance of a model
  (e.g. a new question)
  - A named arg. local which will prevent the form from submitting 
  its data using AJAX.
  - A block that is passed the form object wherein we build 
  the HTML inside the form (e.g. labels, inputs, submisssion buttons, etc)
  All data from the input fields a form built with this will have its 
  name-value nested in a hash named after the class of the passed in model. 
  (e.g. <input name="question[title]"> => { "question": {title: "What is your title?" }})
%>

<%= form_with(model: [@question, @answer], local: true) do |f| %>
  <% if @answer.errors.full_messages.each do |msg| %>
    <ul>
      <li class="text-danger"><%= msg %></li>
    </ul>
    <% end %>
  <% end %>
  <div class="form-group">
    <%= f.text_area(
      :body,
      cols: 50,
      rows: 5,
      placeholder: "What are you thoughts?",
      class: "form-control"
    ) %>
  </div>
  <%= f.submit "Answer", class: "btn-primary" %>
<% end %>

<ul class="list-group answer-list">
  <% @answers.each do |answer| %>
    <li class="list-group-item">
      <p>
        <%= answer.body %><br />
        <% if can? :crud, answer %>
        <small>
          <%= link_to(
            "Delete",
            question_answer_path(@question, answer),
            method: :delete, 
            data: {
              confirm: "Are you sure?"
            },
            class: 'btn btn-danger btn-sm',
          ) %>
        </small>
        |
        <% end %>
        <small>
          Answered <%= time_ago_in_words(answer.created_at) %> By <%= answer.user.first_name %> <%= answer.user.last_name %>
        </small>
      </p>
    </li>
  <% end %>
</ul>